### ISSUE TITLE
fix page.gql to work on a new fresh craft installation

### ISSUE THREAD

**Issue by FabianEllenberger** [wearelucid/vuecid-nuxt-craft#23]
```
...on pageBuilder_button_BlockType {
          __typename
          button {
            url
            customText
            text
            type
            title
            target
          }
        }
```

the traget will throw an error on `yarn dev`

**Comment by Jones-S** [comment]
Related to:
https://github.com/sebastian-lenz/craft-linkfield/issues/80
If linkfield version from newest craft master is taken it is resolved. Will also be resolved as soon as we draft a new packagist version of the craft template.
